flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/App_Icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
name: mana
description: "Ma'na - A Quran study application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  get: ^4.7.2
  flutter_tts: ^3.8.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  screen_protector: ^1.4.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/data.json
    - assets/images/allysoft_logo.png
    - assets/images/loader.gif
    - assets/images/App_Icon.png
    - assets/images/quran_background.jpg
